# AgentMesh Code Intelligence Workflow
# 
# This Kestra workflow demonstrates the integration between:
# - Kestra's AI Agent (for data summarization and decision making)
# - AgentMesh MCP Server (for executing Cline CLI actions)
#
# The pipeline:
# 1. Fetches data from GitHub (issues, PRs, commits)
# 2. Uses AI to summarize repository health
# 3. Makes intelligent decisions based on the summary
# 4. Triggers Cline via AgentMesh to execute fixes
#
# For AI Agents Assemble Hackathon - Kestra Wakanda Data Award

id: agentmesh-code-intel
namespace: agentmesh

description: |
  AI-powered code intelligence pipeline using Kestra's AI Agent.
  
  This workflow:
  - Summarizes data from GitHub (issues, PRs, code changes)
  - Analyzes repository health using AI
  - Makes decisions on what actions to take
  - Triggers Cline via AgentMesh to execute automated fixes
  
  Demonstrates: Kestra AI Agent → Data Summarization → Decision Making → Action

labels:
  hackathon: ai-agents-assemble
  sponsor: kestra
  integration: agentmesh

inputs:
  - id: github_repo
    type: STRING
    description: GitHub repository (owner/repo format)
    defaults: "N-45div/Agentmesh"
    
  - id: agentmesh_url
    type: STRING
    description: AgentMesh MCP server URL
    defaults: "http://localhost:3001/mcp"
    
  - id: check_type
    type: STRING
    description: Type of check to perform
    defaults: "full"
    allowedValues:
      - full
      - security
      - bugs
      - prs

variables:
  github_api: "https://api.github.com"

triggers:
  # Run daily at 9 AM UTC
  - id: daily_health_check
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 * * *"
    
  # Run on webhook (e.g., when new issue is created)
  - id: on_github_event
    type: io.kestra.plugin.core.trigger.Webhook
    key: "agentmesh-webhook"

tasks:
  # ============================================
  # PHASE 1: DATA COLLECTION
  # Fetch data from multiple GitHub endpoints
  # ============================================
  
  - id: log_start
    type: io.kestra.plugin.core.log.Log
    message: "🚀 Starting AgentMesh Code Intelligence for {{ inputs.github_repo }}"

  - id: fetch_repo_info
    type: io.kestra.plugin.core.http.Request
    uri: "{{ variables.github_api }}/repos/{{ inputs.github_repo }}"
    method: GET
    headers:
      Accept: "application/vnd.github.v3+json"
      User-Agent: "AgentMesh-Kestra"

  - id: fetch_open_issues
    type: io.kestra.plugin.core.http.Request
    uri: "{{ variables.github_api }}/repos/{{ inputs.github_repo }}/issues?state=open&per_page=20"
    method: GET
    headers:
      Accept: "application/vnd.github.v3+json"
      User-Agent: "AgentMesh-Kestra"

  - id: fetch_open_prs
    type: io.kestra.plugin.core.http.Request
    uri: "{{ variables.github_api }}/repos/{{ inputs.github_repo }}/pulls?state=open&per_page=20"
    method: GET
    headers:
      Accept: "application/vnd.github.v3+json"
      User-Agent: "AgentMesh-Kestra"

  - id: fetch_recent_commits
    type: io.kestra.plugin.core.http.Request
    uri: "{{ variables.github_api }}/repos/{{ inputs.github_repo }}/commits?per_page=10"
    method: GET
    headers:
      Accept: "application/vnd.github.v3+json"
      User-Agent: "AgentMesh-Kestra"

  # ============================================
  # PHASE 2: AI SUMMARIZATION
  # Use Kestra's AI Agent to analyze the data
  # ============================================

  - id: ai_summarize_repo
    type: io.kestra.plugin.openai.ChatCompletion
    apiKey: "{{ secret('OPENAI_API_KEY') }}"
    model: "gpt-4"
    messages:
      - role: system
        content: |
          You are an AI Code Intelligence Agent. Your job is to analyze repository data 
          and provide actionable insights. You must:
          
          1. SUMMARIZE the current state of the repository
          2. IDENTIFY priority issues (CRITICAL, HIGH, MEDIUM, LOW)
          3. DECIDE what actions should be taken
          4. RECOMMEND specific fixes
          
          Always respond in this JSON format:
          {
            "summary": "Brief overview of repository health",
            "health_score": "CRITICAL|NEEDS_ATTENTION|MODERATE|HEALTHY",
            "priorities": [
              {"level": "CRITICAL|HIGH|MEDIUM|LOW", "issue": "description", "action": "recommended_action"}
            ],
            "decisions": [
              {"action": "action_name", "reason": "why this action", "urgency": "immediate|soon|later"}
            ],
            "recommendations": ["list", "of", "recommendations"]
          }
          
      - role: user
        content: |
          Analyze this GitHub repository data:
          
          ## Repository Info
          {{ outputs.fetch_repo_info.body }}
          
          ## Open Issues ({{ outputs.fetch_open_issues.body | length }} total)
          {{ outputs.fetch_open_issues.body }}
          
          ## Open Pull Requests ({{ outputs.fetch_open_prs.body | length }} total)
          {{ outputs.fetch_open_prs.body }}
          
          ## Recent Commits
          {{ outputs.fetch_recent_commits.body }}
          
          Provide your analysis in the specified JSON format.

  - id: log_ai_summary
    type: io.kestra.plugin.core.log.Log
    message: |
      📊 AI Summary Generated:
      {{ outputs.ai_summarize_repo.choices[0].message.content }}

  # ============================================
  # PHASE 3: DECISION MAKING
  # Based on AI summary, decide what actions to take
  # ============================================

  - id: check_critical_issues
    type: io.kestra.plugin.core.flow.If
    condition: "{{ outputs.ai_summarize_repo.choices[0].message.content contains 'CRITICAL' }}"
    then:
      - id: handle_critical
        type: io.kestra.plugin.core.flow.Parallel
        tasks:
          # Trigger security audit via AgentMesh
          - id: trigger_security_audit
            type: io.kestra.plugin.core.http.Request
            uri: "{{ inputs.agentmesh_url }}"
            method: POST
            headers:
              Content-Type: "application/json"
              Accept: "application/json"
            body: |
              {
                "jsonrpc": "2.0",
                "id": 1,
                "method": "tools/call",
                "params": {
                  "name": "security_audit",
                  "arguments": {
                    "target": ".",
                    "scope": "full"
                  }
                }
              }
              
          # Log critical alert
          - id: log_critical_alert
            type: io.kestra.plugin.core.log.Log
            message: "🚨 CRITICAL issues detected! Security audit triggered."
            
    else:
      - id: check_high_priority
        type: io.kestra.plugin.core.flow.If
        condition: "{{ outputs.ai_summarize_repo.choices[0].message.content contains 'HIGH' }}"
        then:
          - id: trigger_bug_fix
            type: io.kestra.plugin.core.http.Request
            uri: "{{ inputs.agentmesh_url }}"
            method: POST
            headers:
              Content-Type: "application/json"
              Accept: "application/json"
            body: |
              {
                "jsonrpc": "2.0",
                "id": 2,
                "method": "tools/call",
                "params": {
                  "name": "fix_issues",
                  "arguments": {
                    "target": ".",
                    "issueType": "bugs"
                  }
                }
              }
        else:
          - id: routine_review
            type: io.kestra.plugin.core.http.Request
            uri: "{{ inputs.agentmesh_url }}"
            method: POST
            headers:
              Content-Type: "application/json"
              Accept: "application/json"
            body: |
              {
                "jsonrpc": "2.0",
                "id": 3,
                "method": "tools/call",
                "params": {
                  "name": "review_code",
                  "arguments": {
                    "target": "."
                  }
                }
              }

  # ============================================
  # PHASE 4: GENERATE REPORT
  # Create a health report document
  # ============================================

  - id: generate_health_report
    type: io.kestra.plugin.core.http.Request
    uri: "{{ inputs.agentmesh_url }}"
    method: POST
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    body: |
      {
        "jsonrpc": "2.0",
        "id": 4,
        "method": "tools/call",
        "params": {
          "name": "code_task",
          "arguments": {
            "prompt": "Create a HEALTH_REPORT.md file summarizing: {{ outputs.ai_summarize_repo.choices[0].message.content | replace('\"', '\\\"') | replace('\n', ' ') }}"
          }
        }
      }

  - id: log_completion
    type: io.kestra.plugin.core.log.Log
    message: |
      ✅ AgentMesh Code Intelligence Pipeline Complete!
      
      Summary: {{ outputs.ai_summarize_repo.choices[0].message.content }}

# ============================================
# OUTPUTS
# Data available after workflow completion
# ============================================

outputs:
  - id: ai_analysis
    type: STRING
    description: "AI-generated repository analysis"
    value: "{{ outputs.ai_summarize_repo.choices[0].message.content }}"
    
  - id: actions_taken
    type: STRING
    description: "Actions executed by AgentMesh"
    value: "{{ outputs.check_critical_issues.condition ? 'security_audit' : (outputs.check_high_priority.condition ? 'bug_fix' : 'routine_review') }}"

# ============================================
# ERROR HANDLING
# ============================================

errors:
  - id: on_error
    type: io.kestra.plugin.core.log.Log
    message: "❌ Pipeline failed: {{ error.message }}"
